version: 0.2

env:
 variables:
  TF_VERSION: "0.12.29"

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init -no-color
  build:
    commands:
      - terraform apply -no-color --auto-approve
  post_build:
    commands:
      - echo terraform apply completed on `date`